### PR TITLE
update cfg

### PR DESCRIPTION
**Pull request by lukure**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Thanks

**Comment by lukure** [comment]
Cant find the swap votes? Is there any porblem with that? ;D

**Comment by ChillerDragon** [comment]
> Cant find the swap votes? Is there any porblem with that? ;D

They show up for me. Make sure you vote competitive server first. You did not add those votes to the training server.

**Comment by lukure** [comment]
Found them now. However, I first had to vote for the training settings and then again for the competitive settings. Even after restarting the server I have to do the same again. I have no idea what the problem could be....

**Comment by ChillerDragon** [comment]
> Found them now. However, I first had to vote for the training settings and then again for the competitive settings. Even after restarting the server I have to do the same again. I have no idea what the problem could be....

Okay got it. This is a bug in ddnet-insta you did everything correctly. https://github.com/ZillyInsta/ddnet-insta/issues/88
Might be an annoying one to fix.

**Comment by lukure** [comment]
Ou okay 😉

**Pull request merged**
