### PR TITLE
update cfg

### PR DESCRIPTION
**Pull request by lukure**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Thanks

**Comment by lukure** [comment]
Well, I hope it works ;D. I will test it :)
jxsl helped me a bit with the use of github XD

**Comment by ChillerDragon** [comment]
> Well, I hope it works

testing in production be like

image

**Comment by lukure** [comment]
XD, Looks good in itself only sv_welcome doesn't work...
Is there any way to use more letters-perhaps with a new line?

**Comment by ChillerDragon** [comment]
I proposed to increase the buffer size in ddnet. Lets wait for a response https://github.com/ddnet/ddnet/pull/7784

**Comment by ChillerDragon** [comment]
Okay it got approved. Try restarting the servers it should work now :)

**Comment by lukure** [comment]
yap it works now ;D

**Pull request merged**
